import json
from pathlib import Path
from typing import Any

from packages.shared.schemas import PatchPlan, UpgradeLedgerEntry, UpgradeProposal

PROHIBITED_LEDGER_FIELD_PARTS = {
    "raw_text",
    "credentials",
    "credential",
    "secret",
    "password",
    "api_key",
    "authorization",
    "access_token",
    "refresh_token",
}
MAX_LEDGER_STRING_CHARS = 2000


class LedgerGuardrailError(ValueError):
    pass


def make_ledger_entry(proposal: UpgradeProposal, patch_plan: PatchPlan, status: str = "proposed") -> UpgradeLedgerEntry:
    return UpgradeLedgerEntry(
        ledger_id=f"ledger_{proposal.proposal_id}",
        proposal=proposal,
        patch_plan=patch_plan,
        regression_plan=patch_plan.regression_commands,
        status=status,
        notes=["Generated by planning-only self-improvement loop; no patch, commit, deploy, or verification bypass performed."],
    )


def append_ledger_entry(entry: UpgradeLedgerEntry | dict[str, Any], path: str = ".piko/upgrade_ledger.jsonl") -> None:
    payload = entry.model_dump(mode="json") if hasattr(entry, "model_dump") else dict(entry)
    sanitized_payload, warnings = sanitize_ledger_payload(payload)
    if warnings:
        notes = sanitized_payload.setdefault("notes", [])
        if isinstance(notes, list):
            notes.extend(f"Ledger guardrail: {warning}" for warning in warnings)
        else:
            sanitized_payload["notes"] = [str(notes), *[f"Ledger guardrail: {warning}" for warning in warnings]]
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(sanitized_payload, ensure_ascii=False) + "\n")


def sanitize_ledger_payload(payload: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    warnings: list[str] = []
    return _sanitize_value(payload, path="$", warnings=warnings), warnings


def _sanitize_value(value: Any, path: str, warnings: list[str]) -> Any:
    if isinstance(value, dict):
        sanitized: dict[str, Any] = {}
        for key, child in value.items():
            _ensure_allowed_key(str(key), path)
            sanitized[str(key)] = _sanitize_value(child, f"{path}.{key}", warnings)
        return sanitized
    if isinstance(value, list):
        return [_sanitize_value(child, f"{path}[{index}]", warnings) for index, child in enumerate(value)]
    if isinstance(value, str) and len(value) > MAX_LEDGER_STRING_CHARS:
        warnings.append(f"truncated long string at {path} from {len(value)} to {MAX_LEDGER_STRING_CHARS} characters")
        return value[:MAX_LEDGER_STRING_CHARS]
    return value


def _ensure_allowed_key(key: str, path: str) -> None:
    normalized = key.lower()
    for prohibited in PROHIBITED_LEDGER_FIELD_PARTS:
        if prohibited in normalized:
            raise LedgerGuardrailError(f"Refusing to write ledger payload: prohibited field '{key}' found at {path}.")
